#!/usr/bin/env bash

# cli helper for https://somafm.com/
# save as $HOME/bin/soma or similar
# requires: fzy, mpv

# q to quit mpv, ^c to quit script

FUZZER="fzy -l 50"      # https://github.com/jhawthorn/fzy
PLAYER="mpv --no-video" # https://mpv.io

if ! [ $(command -v $FUZZER) ]; then
	echo "y'all gonna need ${FUZZER%% *}" && exit 0
fi

if ! [ $(command -v $PLAYER) ]; then
	echo "y'all gonna need ${PLAYER%% *}" && exit 0
fi

echo -e "choose a station"

playlist=$(curl -s -X GET https://somafm.com/listen/ |
	grep -h MP3 |
	grep -oh '/.*\.pls' |
	cut -d/ -f 3 |
	sort |
	command $FUZZER)

[[ -z $playlist ]] && echo -e "xoxo" && exit 0

stream=$(curl -s -X GET https://somafm.com/$playlist |
	grep -o http.* |
	head -n 1)

echo "Playing $stream"
command $PLAYER $stream
$0
